from django.urls import path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (me_view, login_view, save_expo_push_token, register_user, chat_users_list, reset_password_confirm_custom,
                    coach_players_attendance_view, coach_matches_view, player_attendance_detail, my_coach_categories, remind_unpaid_orders_view,
                    get_categories, player_trainings_view, add_reaction, delete_training_view, training_attendance_view,
                    set_training_attendance, list_clubs, test_push, create_training_view, user_categories_view, announcement_delete_view,
                    training_detail_view, coach_trainings_view, change_password_view, chat_messages_view, announcement_admin_readers, announcements_admin_list,
                    users_in_club, assign_role, remove_role, categories_in_club, coach_players_view, mark_announcement_read, create_announcement, announcements_list,
                    training_update_view, club_detail, coach_attendance_summary, update_match_view, categories_admin, delete_category,
                    all_players_with_roles, player_trainings_history_view, positions_list, player_matches_view, coach_trainings_view_optimalization,
                    create_match_participation, create_match_view, jersey_numbers_view, club_documents_view, password_reset_generate_for_user, password_reset_request,
                    upload_document, match_delete_view, assign_players_to_category, match_stats_view, match_detail_view,player_trainings_history_view_optimalization,
                    match_nominations_view, player_nominated_matches_view, admin_member_payments, set_training_lock_hours,
                    match_participation_view, club_payment_settings_detail,club_orders_view, orders_bulk_update, announcement_readers,
                    upload_pdf_statement_chatgpt,OrderCreateView, MyOrdersListView,delete_user_from_club,admin_edit_member,
                    set_preferred_role, club_payment_settings_list, member_payments, create_member_payments, payment_qr, set_vote_lock_days, player_matches_filtered_view,
                    update_member_payment, remind_attendance_view, remind_match_attendance_view, orders_payments,generate_payment,
                    admin_member_payments_summary, new_members_without_payments,cancel_order_item_view, order_delete_view, create_jersey_order,
                    check_number, jersey_orders_list, jersey_order_delete_view, jersey_orders_bulk_update, generate_jersey_payment, create_order, remind_unpaid_payments,
                    formation_detail, formations_by_category,add_line_to_formation,formation_player_manage, players_in_category, formation_with_attendance, delete_account_view,training_schedules_list_create,
                    training_schedule_detail,contact_form_view, trial_request_view,
                    training_schedule_run_now, coach_overview_view,
                    training_schedules_process_now,EmailOrUsernameTokenObtainPairView, category_vote_reminder_settings_view,
                    linked_accounts_list_view, linked_account_add_view, linked_account_switch_view, linked_account_delete_view,
)
from . import views_system_admin
urlpatterns = [
    path('me/', me_view, name='me'),
    path('token/', EmailOrUsernameTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', login_view, name="login"),
    path('categories/<int:club_id>/', get_categories, name='get_categories'),
    path('player-trainings/', player_trainings_view, name='player_trainings'),
    path('set-training-attendance/', set_training_attendance, name='set_training_attendance'),
    path("trainings/", create_training_view, name="create-training"),
    path("user-categories/", user_categories_view),
    path('training-detail/<int:training_id>/', training_detail_view, name='training-detail'),
    path("save-token/", save_expo_push_token),
    path('test-push/', test_push),
    path("training/<int:training_id>/", delete_training_view),
    path("training-attendance/<int:training_id>/", training_attendance_view),
    path('coach-players-attendance/', coach_players_attendance_view),
    path('coach-trainings/', coach_trainings_view),
    path('change-password/', change_password_view),
    path('register/', register_user),
    path('clubs/', list_clubs),
    path('chat/<int:user_id>/', chat_messages_view, name='chat-messages'),
    path("chat-users/", chat_users_list),
    path("chat/<int:message_id>/react/", add_reaction, name="add-reaction"),
    path('users-in-club/', users_in_club),
    path('assign-role/', assign_role),
    path('remove-role/', remove_role),
    path('categories-in-club/', categories_in_club),
    path('categories-in-club/', coach_players_view),
    path('categories-in-club/', all_players_with_roles),
    path('categories-in-clubaaa/', all_players_with_roles),
    path("trainings/history/", player_trainings_history_view, name="player-trainings-all"),
    path("positions/", positions_list),
    path('matches/', player_matches_view, name='player_matches'),
    path('matches-coach/', coach_matches_view, name='coach_matches'),
    path('match-participations/', create_match_participation, name='create_match_participation'),
    path("matches/create/", create_match_view),
    path("jersey-numbers/", jersey_numbers_view),
    path("documents/", club_documents_view),
    path('upload-document/', upload_document, name='upload-document'),
    path("match-detail/<int:match_id>/", match_detail_view),
    path("match-nominations/<int:match_id>/", match_nominations_view),
    path('player-nominated-matches/', player_nominated_matches_view, name='player-nominated-matches'),
    path("match-participation/", match_participation_view),
    path("match-stats/<int:match_id>/", match_stats_view, name="match-stats"),
    path('matches/delete/<int:match_id>/', match_delete_view, name='match-delete'),
    path("trainings/<int:training_id>/", training_update_view, name="training-update"),
    path("assign-players-to-category/", assign_players_to_category, name="assign_players_to_category"),
    path("set-preferrd-role/", set_preferred_role, name="set_preferred_role"),
path("set-preferred-role/", set_preferred_role, name="set_preferred_role_correct"),
    path('clubs/<int:club_id>/', club_detail, name='club_detail'),
    path('coach-attendance-summary/', coach_attendance_summary, name='coach_attendance_summary'),
    path('player-attendance/<int:player_id>/', player_attendance_detail),
    path('club-payments-settings/', club_payment_settings_list),
    path('club-payments-settings/<int:pk>/', club_payment_settings_detail),
    path('member-payments/', member_payments),
    path('create-member-payments/', create_member_payments),
    path('member-payments/<int:pk>/', update_member_payment),
    path('admin-member-payments/', admin_member_payments),
    path("upload-pdf-chatgpt/", upload_pdf_statement_chatgpt),
    path("matches_edit/<int:match_id>/", update_match_view),
    path("remind-attendance/", remind_attendance_view),
    path("remind-match-attendance/", remind_match_attendance_view),
    path("admin-member-payments-summary/", admin_member_payments_summary),
    path('new-members-without-payments/', new_members_without_payments, name='new_members_without_payments'),
    path("orders/", OrderCreateView.as_view(), name="order-create"),
    path("my-orders/", MyOrdersListView.as_view(), name="my-orders"),
    path("club-orders/<int:club_id>/", club_orders_view, name="club-orders"),
    path("order-items/<int:item_id>/cancel/", cancel_order_item_view, name="cancel-order"),
    path('orders-payments/', orders_payments),
    path("payment-qr/<str:payment_type>/<int:pk>/", payment_qr, name="payment_qr"),
    path("order/<int:order_id>/generate-payment/", generate_payment),
    path("orders/bulk-update/", orders_bulk_update, name="orders-bulk-update"),
    path("order/<int:order_id>/delete/", order_delete_view, name="order-delete"),
    path("clubs/<int:club_id>/check-number/<int:number>/", check_number, name="check_number"),
    path("orders/jersey/", create_jersey_order, name="create_jersey_order"),
    path("clubs/<int:club_id>/jersey-orders/", jersey_orders_list, name="jersey_orders_list"),
    path("jersey-orders/bulk-update/", jersey_orders_bulk_update),
    path("jersey-orders/<int:order_id>/delete/", jersey_order_delete_view),
    path("jersey-orders/<int:order_id>/generate-payment/", generate_jersey_payment, name="generate_jersey_payment"),
    path("orders_ludimus/", create_order, name="create_order"),
    path("delete-user-from-club/<int:user_id>/", delete_user_from_club, name="delete-user-from-club"),
    path("categories-admin/", categories_admin, name="categories-admin"),
    path("delete-category/<int:category_id>/", delete_category, name="delete-category"),
    path("set-vote-lock-days/", set_vote_lock_days, name="set_vote_lock_days"),
    path("set-training-lock-hours/", set_training_lock_hours),
    path("announcements/", announcements_list, name="announcements_list"),
    path("announcements/create/", create_announcement, name="create_announcement"),
    path("announcements/<int:pk>/read/", mark_announcement_read, name="mark_announcement_read"),
    path("announcements/<int:pk>/readers/", announcement_readers, name="announcement_readers"),
    path("announcements-admin/", announcements_admin_list, name="announcements_admin_list"),
    path("announcements-admin/<int:pk>/readers/", announcement_admin_readers, name="announcement_admin_readers"),
    path("password_reset/confirm_custom/", reset_password_confirm_custom, name="password_reset_confirm_custom"),
    path("password_reset/request/", password_reset_request, name="password_reset_request"),
    path("password_reset/generate_for_user/", password_reset_generate_for_user, name="password_reset_generate_for_user"),
    path("my-coach-categories/", my_coach_categories, name="my_coach_categories"),
    path("announcements-delete/<int:pk>/", announcement_delete_view, name="announcement-delete"),
    path("formations/<int:category_id>/", formations_by_category),
    path("formation/<int:formation_id>/", formation_detail),
    path("formation/<int:formation_id>/add-line/", add_line_to_formation),
    path("formation-line/<int:line_id>/player/", formation_player_manage),
    path("players-in-category/<int:category_id>/", players_in_category),
    path("formations-with-attendance/<int:category_id>/<int:training_id>/", formation_with_attendance),
    path("delete-account/", delete_account_view, name="delete-account"),
    path("admin-member/<int:pk>/", admin_edit_member, name="admin-edit-member"),
    path("matches_filtered/", player_matches_filtered_view, name="matches_filtered"),
    path("trainings_optimalization/history/", player_trainings_history_view_optimalization, name="player_trainings_history_view_optimalization"),
    path('coach-trainings-optimalization/', coach_trainings_view_optimalization),
    path("jersey-orders/remind-unpaid/", remind_unpaid_orders_view),
    path("admin-member-payments/remind-unpaid/", remind_unpaid_payments),
    path("training-schedules/", training_schedules_list_create, name="training-schedules"),
    path("training-schedules/<int:schedule_id>/", training_schedule_detail, name="training-schedule-detail"),
    path("training-schedules/<int:schedule_id>/run-now/", training_schedule_run_now, name="training-schedule-run-now"),
    path("training-schedules/process-now/", training_schedules_process_now, name="training-schedules-process-now"),
    path('contact-form/', contact_form_view, name='contact_form'),
    path("trial-request/", trial_request_view, name="trial-request"),
    path('coach-overview/', coach_overview_view, name='coach_overview'),
    path("category-vote-reminder-settings/",category_vote_reminder_settings_view,name="category-vote-reminder-settings",),
    path("linked-accounts/", linked_accounts_list_view, name="linked-accounts-list"),
    path("linked-accounts/add/", linked_account_add_view, name="linked-accounts-add"),
    path("linked-accounts/switch/", linked_account_switch_view, name="linked-accounts-switch"),
    path("linked-accounts/<int:user_id>/", linked_account_delete_view, name="linked-accounts-delete"),
    path("admin-member-payments/<int:pk>/",update_member_payment, name="update_member_payment"),
    
    # SYSTEM ADMIN
    path("system-admin/overview/", views_system_admin.system_admin_overview, name="system-admin-overview"),

    path("system-admin/clubs/", views_system_admin.system_admin_clubs, name="system-admin-clubs"),
    path("system-admin/clubs/<int:club_id>/", views_system_admin.system_admin_club_detail, name="system-admin-club-detail"),

    path("system-admin/users/", views_system_admin.system_admin_users, name="system-admin-users"),
    path("system-admin/users/<int:user_id>/", views_system_admin.system_admin_user_detail, name="system-admin-user-detail"),

    path("system-admin/member-payments/", views_system_admin.system_admin_member_payments, name="system-admin-member-payments"),
    path("system-admin/member-payments/<int:payment_id>/", views_system_admin.system_admin_member_payment_detail, name="system-admin-member-payment-detail"),

    path("system-admin/orders/", views_system_admin.system_admin_orders, name="system-admin-orders"),
    path("system-admin/orders/<int:order_id>/", views_system_admin.system_admin_order_detail, name="system-admin-order-detail"),

    path("system-admin/club-usage/", views_system_admin.system_admin_club_usage, name="system-admin-club-usage"),



]

